BOOLCONFVARS_ON=	BUNDLED_POSER WITH_POSER_ATOMICS WITH_MAN \
			CRED_EXEC CRED_FILE CRED_PAM CRED_POW
BOOLCONFVARS_OFF=	WITH_POSER_POLL WITH_POSER_EVPORTS WITH_POSER_EPOLL \
			WITH_POSER_KQUEUE \
			WITH_POSER_EVENTFD WITH_POSER_SIGNALFD \
			WITH_POSER_TIMERFD \
			WITHOUT_POSER_EVPORTS WITHOUT_POSER_EPOLL \
			WITHOUT_POSER_KQUEUE \
			WITHOUT_POSER_EVENTFD WITHOUT_POSER_SIGNALFD \
			WITHOUT_POSER_TIMERFD
SINGLECONFVARS=		MANFMT OPENSSLINC OPENSSLLIB POSER_FD_SETSIZE

DEFAULT_POSER_FD_SETSIZE=	4096

USES=			gen man pkgconfig sub

SUBBUILD=		BIN2CSTR MKCLIDOC

BIN2CSTR_TARGET=	tools/bin/bin2cstr
BIN2CSTR_SRCDIR=	tools/bin2cstr
BIN2CSTR_MAKEARGS=	DESTDIR=../bin prefix= bindir= \
			HOSTBUILD=1 PORTABLE=1 STATIC=0
BIN2CSTR_MAKEGOAL=	install
BIN2CSTR_CLEANGOAL=	distclean

MKCLIDOC_TARGET=	tools/bin/mkclidoc
MKCLIDOC_SRCDIR=	tools/mkclidoc
MKCLIDOC_MAKEARGS=	DESTDIR=../bin prefix= bindir= zimkdir=../../zimk \
			HOSTBUILD=1 PORTABLE=1 STATIC=0
MKCLIDOC_MAKEGOAL=	install
MKCLIDOC_CLEANGOAL=	distclean

DISTCLEANDIRS=		tools/bin
NODIST=			poser/zimk \
			tools/mkclidoc/zimk \
			$(wildcard poser/src/lib/core/contrib/xxHash/[!x]*)

include zimk/zimk.mk

ifeq ($(BUNDLED_POSER),1)
WITH_ATOMICS:=		$(WITH_POSER_ATOMICS)
WITH_POLL:=		$(WITH_POSER_POLL)
WITH_EVPORTS:=		$(WITH_POSER_EVPORTS)
WITH_EPOLL:=		$(WITH_POSER_EPOLL)
WITH_KQUEUE:=		$(WITH_POSER_KQUEUE)
WITH_EVENTFD:=		$(WITH_POSER_EVENTFD)
WITH_SIGNALFD:=		$(WITH_POSER_SIGNALFD)
WITH_TIMERFD:=		$(WITH_POSER_TIMERFD)
WITH_TLS:=		1
WITHOUT_EVPORTS:=	$(WITHOUT_POSER_EVPORTS)
WITHOUT_EPOLL:=		$(WITHOUT_POSER_EPOLL)
WITHOUT_KQUEUE:=	$(WITHOUT_POSER_KQUEUE)
WITHOUT_EVENTFD:=	$(WITHOUT_POSER_EVENTFD)
WITHOUT_SIGNALFD:=	$(WITHOUT_POSER_SIGNALFD)
WITHOUT_TIMERFD:=	$(WITHOUT_POSER_TIMERFD)
FD_SETSIZE:=		$(POSER_FD_SETSIZE)
posercore_BUILDWITH:=	#
posercore_STRIPWITH:=	#
posercore_INSTALLWITH:=	#
posercore_PRECFLAGS:=	-I./poser/include
$(call zinc, poser/src/lib/core/core.mk)
endif

GEN_BIN2CSTR_tool=	$(BIN2CSTR_TARGET)
GEN_BIN2CSTR_args=	$1 $2
GEN_CHELP_tool=		$(MKCLIDOC_TARGET)
GEN_CHELP_args=		-fcpp -o$1 $2
GEN_MAN_tool=		$(MKCLIDOC_TARGET)
GEN_MAN_args=		-f$(MANFMT) -o$1 $2
GEN_MAN8_tool=		$(MKCLIDOC_TARGET)
GEN_MAN8_args=		-f$(MANFMT),sect=8 -o$1 $2
MANFMT:=		$(or $(MANFMT),$(if \
			$(findstring BSD,$(SYSNAME)),mdoc,man))

ifeq ($(CRED_FILE),1)
$(call zinc, src/lib/swadbcrypt/swadbcrypt.mk)
endif

$(call zinc, src/bin/swad/swad.mk)

ifeq ($(CRED_FILE),1)
$(call zinc, src/bin/swadpw/swadpw.mk)
endif

ifeq ($(CRED_PAM),1)
$(call zinc, src/libexec/swad_pam/swad_pam.mk)
endif
