name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        cred_exec: [on, off]
        cred_file: [on, off]
        cred_pam: [on, off]
    runs-on: ubuntu-latest
    env:
      CI_CFLAGS: -O2 -std=c11 -Wall -Wextra -Wshadow -Werror -pedantic
      CI_DEPS: libpam0g-dev
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build-depends
      run: sudo apt-get -y install ${CI_DEPS}
    - name: make
      run: >-
        make -j CFLAGS="${CI_CFLAGS}" CRED_EXEC=${{matrix.cred_exec}}
        CRED_FILE=${{matrix.cred_file}} CRED_PAM=${{matrix.cred_pam}}
