name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        cred_exec: [CRED_EXEC=on, CRED_EXEC=off]
        cred_file: [CRED_FILE=on, CRED_FILE=off]
        cred_pam: [CRED_PAM=on, CRED_PAM=off]
        cred_pow: [CRED_POW=on, CRED_POW=off]
    runs-on: ubuntu-latest
    env:
      CI_CFLAGS: -O2 -std=c11 -Wall -Wextra -Wshadow -Werror -pedantic
      CI_DEPS: libpam0g-dev
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build-depends
      run: sudo apt-get -y install ${CI_DEPS}
    - name: make
      run: >-
        make -j CFLAGS="${CI_CFLAGS}"
        ${{matrix.cred_exec}}
        ${{matrix.cred_file}}
        ${{matrix.cred_pam}}
        ${{matrix.cred_pow}}
